apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation
  namespace: gongxf
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: presentation
        image: nginx:1.14.2